# Option 1 : créer le conteneur docker via le module command
---
- hosts: all
  become: true

  tasks:
  - name: création du conteneur docker via la commande docker
    command: docker run -d --name simple-devops-container -p 8080:8080 simple-devops-image

# option 2 : créer le conteneur docker via le module docker_container
#  tasks:
#  - name: création du conteneur simple-devops-container
#    docker_container:
#      name: simple-devops-container
#      image: simple-devops-image
#      state: present
#      recreate: yes
#      ports:
#        - "8080:8080"
