# Option 1 : créer l'image docker via le module command
---
- hosts: all
  become: true
  tasks:
  - name: construction de l'image docker
    command: docker build -t simple-devops-image .
    args:
      chdir: /opt/docker

# option 2 : créer l'image docker via le module docker_image

#  tasks:
#  - name: construction de l'image docker
#    docker_image:
#      build:
#        path: /opt/docker
#      name: simple-devops-image
#     tag: v1
#     source: build
