---
- hosts: all
  become: true
  tasks:
  - name: arrêter l'ancien conteneur docker s'il existe
    command: docker stop simple-devops-container
    ignore_errors: yes

  - name: supprimer le conteneur docker arrêté
    command: docker rm simple-devops-container
    ignore_errors: yes

  - name: supprimer l'image docker actuelle
    command: docker rmi simple-devops-image
    ignore_errors: yes
#    register: result
#    failed_when:
#      - result.rc == 0
#      - '"docker" not in result.stdout'


  - name: construction de l'image docker
    command: docker build -t simple-devops-image .
    args:
      chdir: /opt/docker

  - name: création du conteneur docker
    command: docker run -d --name simple-devops-container -p 8080:8080 simple-devops-image

