---
- hosts: ansible

  tasks:
  - name: créer l'image docker
    command: docker build -t regapp:latest .
    args:
     chdir: /opt/docker

  - name: créer le tag pour pousser l'image sur dockerhub
    command: docker tag regapp:latest 2randi/regapp:latest

  - name: pousser l'image docker
    command: docker push 2randi/regapp:latest

