---
- hosts: kubernetes
#  become: ture
  user: root

  tasks:
    - name: déployer regapp sur kubernetes
      command: kubectl apply -f regapp-deploy.yml

    - name: créer le service pour regapp
      command: kubectl apply -f regapp-service.yml

    - name: mettre à jour le déploiement avec de nouveaux pods si l'image a changé sur docker hub
      command: kubectl rollout restart deployment.apps/regapp-deployment

